# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

consumer_key: dj0yJmk9TVZsQThOUmVYWFZuJmQ9WVdrOU5XUndZVVo2Tm5FbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1lYg
consumer_secret: 37580f718fe723c05de1f6562572177255c8b83f
league_number: 358796
game_key: 371

ffn_api_key: uhyvmrjd4ydr