# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

consumer_secret: 'bed6d08509231dbd628250613ae1df725117472f'
league_number: '358796'
game_key: '371'
ffn_api_key: 'uhyvmrjd4ydr'
secret_token: 'ABYQ9VltPhjq_oQC2t_TVOeonGYTzkAXcz1RVAGcXoiKtJzyHEavvrW5xJw-'
token: 'BVLpjaHOsln0TEuheEQYZ1T1PjuV_M.GNuCx_3PYSrhuVgoveJGMfCFTZNn32HjBRio6TyQrjr_uTgccXv8ZhZzn8bWEykC82ob_IQOFDZn7g_pZh2U_kvZH6aZq_wtDGicnqGIEh8bWYLw7IkPn4fr8TrfAplzXAf_D8WLC4lwJB0pZdWHBTokGrr29ynVMRCfxe48_r.pT_iiSkd58Xzfn_JVSMW.6QTT4rTGFdRlltZ2VAWmsWNjlFgBnHfAUUKFh.fkWBwIUheq.qomTkuq4l9PvRLyC.hPLezD.dpwiWRUEIcM_gIAsjW0eDVbg_GYzuYzfqnCQ678nQJ80FWpU8.Sgflpa2kgeJuAb2UA_2fFVGm8SabCoZO8FgSKv5JbLwMTqXVOjDQPRi4d0OTUs3uGC.ZITDzCCOz9h4x88be2mRrYG5Xzl6QxZP8KGOpjQ5gGAlh41r1HwforfHiMnzhNDSOSnydXUBwFRmBbJoyEovsnrTBmRA0v9ae2PEJ9jHA_IdA.ZtPCp_WnjFP_q2c56bfI2rqB20RwouPe61zbpiaw1viep1JQvQQY4_gpLrM.7npir6ZyxuETdN8rG2p02zsHZf4w4n_bUKxDjNSzv1xdVDXjl.8us9xM8tOBE8C1miyXQT34OfmDXKtAd_5ZEO.qmS5V1TWsAKA1Y.mkhORBtzHTFegQUwhmiesXcDXkGAGps7Kd2nWr4ZLGaVPrwJkD.0x1SxXkU.PIUnRJv3gEPpd3pGfGSzzo9DoEh8VM4N7xFFSul0X6Lkh_5I_40tvMnHSj_loSA2NmZeJtpn86TmtHh0b1pW1wdw3POEZW7xm5tLm2e_6X6VSNBEZ8t..P4W6d6fs32BgFyTASQHPzrQi8dTWwO.xQLAvTfE2h2XCry5j.27y_F2jLpiuTpNOG9k5WlKjwidqWB7rAQT0BcpsFmoVnfvSb31y3muMyEEbpHlgnJIhgdiR_dfhE9nPCfGoPFTNrxG4K2tB_JOeozRhJDJZK5opuaBQdAER37z1FseZHO8L9kBI5LCJcPMP4JZhVNy7Edfhwv6d.1nb7rxU_XJ5nhbItowqsHST2WNeMTL3Ci'
code: '5kadcp6'
refresh_token: 'ABYQ9VltPhjq_oQC2t_TVOeonGYTzkAXcz1RVAGcXoiKtJzyHEavvrW5xJw-'
consumer_key: 'dj0yJmk9Y1hWZEd0aHY2ZHBJJmQ9WVdrOWNtVkhaR3RvTm5NbWNHbzlNVFl5TmpZNE1qTTJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD00Nw--'